import styles from "@/styles/Home.module.css";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [downloadsData, setDownloadsData] = useState<string>("");
  const [inputField, setInputField] = useState<string>("");

  const getDownloads = async () => {
    const res = await fetch("http://localhost:3000/api/getDownloads", {
      method: "POST",
      body: JSON.stringify({ inputField }),
    });
    const { downloads } = await res.json();
    setDownloadsData(downloads);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="flex h-screen w-screen items-center justify-center">
          <div className="flex flex-col items-center gap-6">
            <input
              type="text"
              value={inputField}
              onChange={(e) => setInputField(e.target.value)}
              className="rounded-md border-2 border-gray-300 p-2"
              placeholder="Enter package name"
            />
            <button
              onClick={getDownloads}
              type="button"
              className="rounded-md bg-pink-600 p-4 text-xl"
            >
              Go
            </button>
            {downloadsData && (
              <p className="text-white pt-10">Data: {downloadsData}</p>
            )}
          </div>
        </div>
      </main>
    </>
  );
}
